---
title: "Data Exploration"
author: "Mahir Shariar Ratul"
date: "`r Sys.Date()`"
output:
  html_notebook: default
  pdf_document: default
---

# Univariate Exploration

# Load the Iris Dataset
```{r}
# Load dataset
data(iris)

# View first few rows
head(iris)

```

# Summary Statistics
```{r}
# Summary of numeric variables
summary(iris)

```
# Univariate Plots
```{r}
# Histogram (Distribution of a Numeric Variable)
# Histogram of Sepal Length
hist(iris$Sepal.Length, 
     main="Histogram of Sepal Length", 
     col="lightblue", 
     xlab="Sepal Length", 
     border="black")

```
```{r}
# Density plot of Petal Length
# Density Plot (Smooth Distribution)
plot(density(iris$Petal.Length), 
     main="Density Plot of Petal Length", 
     col="blue", 
     lwd=2)
```
```{r}
hist(iris$Sepal.Width, 
     main="Histogram of Sepal width", 
     col="lightblue", 
     xlab="Sepal Length", 
     border="black")

```
```{r}
hist(iris$Petal.Length, 
     main="Histogram of Petal Length", 
     col="red", 
     xlab="petal Length", 
     border="black")

```


```

```
```{r}
hist(iris$Petal.Width, 
     main="Histogram of Petal width", 
     col="cyan", 
     xlab="Petal width", 
     border="black")

```




```{r}

# Density plot of Petal Length
# Density Plot (Smooth Distribution)
plot(density(iris$Sepal.Length), 
     main="Density Plot of sepal Length", 
     col="cyan", 
     lwd=2)
```


```{r}

# Density plot of Petal Length
# Density Plot (Smooth Distribution)
plot(density(iris$Petal.Width), 
     main="Density Plot of Petal width", 
     col="violet", 
     lwd=2)
```


```{r}
#Box Plot (Identifying Outliers)
# Boxplot of Sepal Width
boxplot(iris$Petal.Width, 
        main="Box Plot of petal Width", 
        col="yellow")

```


```{r}
# Box Plot (Identifying Outliers)
# Boxplot of Sepal Width
boxplot(iris$Sepal.Width, 
        main="Box Plot of Sepal Width", 
        col="orange")


# Exploring Categorical Data

```

```{r}
# Box Plot (Identifying Outliers)
# Boxplot of Sepal Width
boxplot(iris$Petal.Length, 
        main="Box Plot of Petal Length", 
        col="red")


```


```{r}
# Bar plot for Species count
barplot(table(iris$Species), 
        main="Count of Each Species", 
        col=c("violet", "cyan", "pink"))

```
# Multivariate Exploration
# Scatter Plot (Numeric vs. Numeric)
```{r}
# Scatter plot: Sepal Length vs. Sepal Width
plot(iris$Sepal.Length, iris$Sepal.Width, 
     main="Scatter Plot of Sepal Length vs Sepal Width",
     xlab="Sepal Length", ylab="Sepal Width",
     col=iris$Species, pch=19)
legend("topright", legend=levels(iris$Species), col=1:3, pch=19)

```

# Correlation (Numeric vs. Numeric)
```{r}
# Correlation between Sepal Length and Petal Length
cor(iris$Sepal.Length, iris$Petal.Length)

```

```{r}
# Correlation matrix
cor(iris[,1:3])

```

# Box Plot (Numeric vs. Categorical)
```{r}
# Box plot of Petal Length by Species
boxplot(Sepal.Length ~ Species, data=iris,
        main="Box Plot of Sepal Length by Species",
        col=c("red", "green", "blue"))
```


```{r}
# Box plot of Petal Length by Species
boxplot(Petal.Width ~ Species, data=iris,
        main="Box Plot of Petal width by Species",
        col=c("red", "green", "pink"))
```


```{r}
# Box plot of Petal Length by Species
boxplot(Petal.Length ~ Species, data=iris,
        main="Box Plot of Petal Length by Species",
        col=c("yellow", "orange", "green"))

```
# Pair Plot (Multivariate Visualization)
```{r}
# Pair plot (Scatter plot matrix)
pairs(iris[,1:4], col=iris$Species, pch=19)

```
# Using ggplot2 for Enhanced Visualization
```{r}
# Load ggplot2
library(ggplot2)

# Scatter plot with regression line
ggplot(iris, aes(x=Sepal.Length, y=Petal.Length, color=Species)) +
  geom_point() +
  geom_smooth(method="lm", se=FALSE) +
  ggtitle("Sepal Length vs Petal Length by Species")

```
